POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Die Hardman",
    "number": "007-004-1776"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "No Number Jones"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "No name, no number, no service"
}